# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 416)
        MainWindow.setMinimumSize(QtCore.QSize(628, 416))
        MainWindow.setMaximumSize(QtCore.QSize(628, 416))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(189, 189, 142);\n"
"\n"
"font: 14pt \"MV Boli\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(40, 150, 261, 41))
        self.generate.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(170, 170, 127);\n"
"box-shadow:5px 5px 5px grey;\n"
"border: 2px solid #969670;\n"
"")
        self.generate.setAutoDefault(False)
        self.generate.setDefault(False)
        self.generate.setFlat(False)
        self.generate.setObjectName("generate")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(340, 40, 251, 221))
        self.result.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(40, 220, 261, 41))
        self.save.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(170, 170, 127);\n"
"box-shadow:5px 5px 5px grey;\n"
"border: 2px solid #969670;\n"
"")
        self.save.setObjectName("save")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(340, 290, 251, 41))
        self.clear.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(170, 170, 127);\n"
"box-shadow:5px 5px 5px grey;\n"
"border: 2px solid #969670;")
        self.clear.setObjectName("clear")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(40, 290, 261, 41))
        self.exit.setStyleSheet("border-radius: 10px;\n"
"\n"
"background-color: rgb(170, 170, 127);\n"
"box-shadow:5px 5px 5px grey;\n"
"border: 2px solid #969670;\n"
"")
        self.exit.setObjectName("exit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 80, 261, 41))
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"\n"
"box-shadow:5px 5px 5px grey;\n"
"border: 2px solid #969670;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR Code Generator"))
        self.label.setText(_translate("MainWindow", "Your Data For QR Code"))
        self.generate.setText(_translate("MainWindow", "Generate QR Code"))
        self.result.setText(_translate("MainWindow", "Here QR Code "))
        self.save.setText(_translate("MainWindow", "Save QR Code Image"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.exit.setText(_translate("MainWindow", "Exit"))
